### ISSUE TITLE
Filter exception classes

### ISSUE THREAD

**Issue by MrMitch** [chteuchteu/SymfonyExceptions2GitLabIssuesBundle#4]
Some exceptions might not be interesting to log. Having a way to filter which exception should not be logged might be useful (kinda like a blacklist).
For example, when a user tries to access a page when he is not logged-in, Symfony will throw a `Symfony\Component\Security\Core\Exception\AccessDeniedException` and redirect the user to the login page. If he logs-in successfully, he will be taken to the page he originally wanted to see.
With the actual implementation, every time the `AccessDeniedException` is thrown, a new issue is created or the count is updated in the existing issue (re-opening it if it was closed), leading to things like 

![image](https://cloud.githubusercontent.com/assets/576772/18947722/84cf2a20-8634-11e6-985c-f757e3f0948f.png)

These issues create more noise than meaningful informations.

**Comment by quentin-st** [comment]
You can use the `excluded_exceptions` config item, which acts as a blacklist. The exemple provided in the documentation only mentions symfony's `NotFoundHttpException`, but you can add the `AccessDeniedException` like this:

```
sym_exc_2_gtlb_isu_bndle:
    gitlab_api_url: https://gitlab.com/api/v3/
    gitlab_token: (put your token here)
    project: your_project_name
    excluded_exceptions:
        - Symfony\Component\HttpKernel\Exception\NotFoundHttpException
        - Symfony\Component\Security\Core\Exception\AccessDeniedException
```
